export const universities = [
  '가천대학교',
  '건국대학교',
  '경북대학교',
  '경희대학교',
  '고려대학교1',
  '고려대학교2',
  '고려대학교3',
  '고려대학교4','고려대학교5',
  '고려대학교6','고려대학교7',
  '고려대학교8','고려대학교9',
  '고려대학교10','고려대학교11',
  '고려대학교12','고려대학교13',
  '고려대학교14','고려대학교15',
  '고려대학교16','고려대학교17',
  '고려대학교18','고려대학교19',
  '고려대학교20','고려대학교21',
  '고려대학교(세종 캠퍼스)',
  '국민대학교',
  '동국대학교',
  '부산대학교',
  '서강대학교',
  '서울과학기술대학교',
  '서울대학교',
  '서울시립대학교',
  '성균관대학교',
  '세종대학교',
  '숙명여자대학교',
  '숭실대학교',
  '아주대학교',
  '연세대학교',
  '연세대학교(미래캠퍼스)',
  '이화여자대학교',
  '인하대학교',
  '전남대학교',
  '전북대학교',
  '중앙대학교',
  '충남대학교',
  '충북대학교',
  '한국외국어대학교',
  '한양대학교',
  '한양대학교 ERICA',
  '홍익대학교',
];

export const departments = [
  '경영학과',
  '경제학과',
  '국어국문학과',
  '기계공학과',
  '도시공학과',
  '물리학과',
  '미디어학부',
  '법학과',
  '사학과',
  '산업공학과',
  '생명공학과',
  '서어서문학과',
  '소프트웨어학과',
  '수학과',
  '신소재공학과',
  '심리학과',
  '언론정보학과',
  '영어영문학과',
  '의예과',
  '인공지능학과',
  '자유전공학부',
  '전기전자공학부',
  '정치외교학과',
  '정보보호학과',
  '정치시기 학과',
  '정밀시기 학과',
  '정밀기계공학과',
  '철학과',
  '컴퓨터공학과',
  '통계학과',
  '화학과',
  '환경공학과',
];

export const admissionYears = Array.from({ length: 18 }, (_, index) => 2018 + index);

export const verificationCodeAnswer = '123456';
export const verificationDurationSeconds = 30 * 60;

export const universityEmailDomains: Record<string, string> = {
  가천대학교: 'gachon.ac.kr',
  건국대학교: 'konkuk.ac.kr',
  경북대학교: 'knu.ac.kr',
  경희대학교: 'khu.ac.kr',
  고려대학교: 'korea.ac.kr',
  국민대학교: 'kookmin.ac.kr',
  동국대학교: 'dongguk.edu',
  부산대학교: 'pusan.ac.kr',
  서강대학교: 'sogang.ac.kr',
  서울과학기술대학교: 'seoultech.ac.kr',
  서울대학교: 'snu.ac.kr',
  서울시립대학교: 'uos.ac.kr',
  성균관대학교: 'skku.edu',
  세종대학교: 'sejong.ac.kr',
  숙명여자대학교: 'sookmyung.ac.kr',
  숭실대학교: 'soongsil.ac.kr',
  아주대학교: 'ajou.ac.kr',
  연세대학교: 'yonsei.ac.kr',
  이화여자대학교: 'ewha.ac.kr',
  인하대학교: 'inha.edu',
  전남대학교: 'jnu.ac.kr',
  전북대학교: 'jbnu.ac.kr',
  중앙대학교: 'cau.ac.kr',
  충남대학교: 'cnu.ac.kr',
  충북대학교: 'chungbuk.ac.kr',
  한국외국어대학교: 'hufs.ac.kr',
  한양대학교: 'hanyang.ac.kr',
  홍익대학교: 'hongik.ac.kr',
};
