export const COMMON_ERROR_CODES = {
  NETWORK_ERROR: 'COMMON_NETWORK_ERROR',
  INVALID_RESPONSE: 'COMMON_INVALID_RESPONSE',
  UNKNOWN: 'COMMON_UNKNOWN',
} as const;

export const AUTH_ERROR_CODES = {
  UNAUTHORIZED: 'AUTH_UNAUTHORIZED',
  ACCESS_TOKEN_EXPIRED: 'AUTH_ACCESS_TOKEN_EXPIRED',
  REFRESH_TOKEN_EXPIRED: 'AUTH_REFRESH_TOKEN_EXPIRED',
  REFRESH_TOKEN_MISSING: 'AUTH_REFRESH_TOKEN_MISSING',
  REFRESH_FAILED: 'AUTH_REFRESH_FAILED',
  SESSION_EXPIRED: 'AUTH_SESSION_EXPIRED',
} as const;

export const UNIVERSITY_ERROR_CODES = {} as const;
export const DEPARTMENT_ERROR_CODES = {} as const;
export const POST_ERROR_CODES = {} as const;
export const COMMENT_ERROR_CODES = {} as const;
export const USER_ERROR_CODES = {} as const;
export const MYPAGE_ERROR_CODES = {} as const;

export const DOMAIN_ERROR_CODES = {
  auth: AUTH_ERROR_CODES,
  comment: COMMENT_ERROR_CODES,
  common: COMMON_ERROR_CODES,
  department: DEPARTMENT_ERROR_CODES,
  mypage: MYPAGE_ERROR_CODES,
  post: POST_ERROR_CODES,
  university: UNIVERSITY_ERROR_CODES,
  user: USER_ERROR_CODES,
} as const;
