export const COMMON_ERROR_CODES = {
  NETWORK_ERROR: 'COMMON_NETWORK_ERROR',
  INVALID_RESPONSE: 'COMMON_INVALID_RESPONSE',
  UNKNOWN: 'COMMON_UNKNOWN',
} as const;

export const AUTH_ERROR_CODES = {
  UNAUTHORIZED: 'AUTH_UNAUTHORIZED',
  ACCESS_TOKEN_EXPIRED: 'AUTH_ACCESS_TOKEN_EXPIRED',
  REFRESH_TOKEN_EXPIRED: 'AUTH_REFRESH_TOKEN_EXPIRED',
  REFRESH_TOKEN_MISSING: 'AUTH_REFRESH_TOKEN_MISSING',
  REFRESH_FAILED: 'AUTH_REFRESH_FAILED',
  SESSION_EXPIRED: 'AUTH_SESSION_EXPIRED',
} as const;
